import type { Metadata } from "next";
import { M_PLUS_Rounded_1c as mplus } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mplusFont = mplus({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${mplusFont.className} antialiased`}>{children}</body>
    </html>
  );
}
